name: OS Build Dispatcher
on: [push]

jobs:
  trigger-build:
    runs-on: codeberg-small
    steps:
      - name: Trigger GitHub workflow for all packages
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/rXelelo/codeberg-builder/dispatches \
            -d '{"event_type":"build-arch"}'
